module.exports = {
    trailingComma: "es5",
    tabWidth: 4,
    semi: true,
    singleQuote: false,
    printWidth: 100,
    useTabs: false,
    proseWrap: "always",
    quoteProps: "as-needed",
    bracketSameLine: false,
    jsxSingleQuote: false,
    bracketSpacing: true,
    bracketSameLine: false,
    arrowParens: "avoid",
    proseWrap: "never",
};
